id: test-batch-service-packed
kind: InferenceService
spec:
  args:
    - /opt/app/predictor.py
  command:
    - python
  image: <past-image>
  modelSource:
    connection: models-output
    path: test-data/batch_job_data/model.tar.gz
