kind: InferenceJob
spec:
  inferenceServiceId: test-batch-service-embedded
  dataSource:
    connection: models-output
    path: test-data/batch_job_data/input
  outputDestination:
    connection: models-output
    path: test-data/output-embedded
