id: test-batch-service
kind: InferenceService
spec:
  args:
    - /opt/app/predictor.py
  command:
    - python
  image: <past-image>
  modelRegistry:
    remote:
      modelConnection: models-output
      modelPath: test-data/batch_job_data/model
