version: 2.1

jobs:
  check-vulnerabilities:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo make install-vulnerabilities-checker
      - run: make check-vulnerabilities

workflows:
  main:
    jobs:
      - check-vulnerabilities

