kind: ModelTraining
id: dogs-cats-classifier
spec:
  model:
    name: dogs_cats
    version: 1
  toolchain: mlflow-gpu
  entrypoint: main
  workDir: mlflow/keras/dogs_cats
  data:
    - connName: models-output
      remotePath: /input/PetImages
      localPath: mlflow/keras/dogs_cats/PetImages
  resources:
    limits:
      gpu: 1
      cpu: 4
      memory: 16Gi
    requests:
      gpu: 1
      cpu: 4
      memory: 16Gi
  vcsName: odahu-flow-examples
  reference: feat/dogs-cats-example
