id: wine
kind: ModelTraining
spec:
  model:
    name: wine
    version: 1.0
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/sklearn/wine
  # READ - ONLY
  featureSource:
    - connName: features-source #(bucket: odahu-demo01-feature-store)
      localPath: wpm-model/rc01/
      namespace: ...
  # READ - ONLY
  algorithmSource:
    connName: algorithms-source
  # WRITE - ONLY
  modelRegistry:
    connName: models-registry
  hyperParameters:
    alpha: "1.0"
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi


